# Generated by Django 2.0 on 2018-03-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wpposts',
            name='post_status',
            field=models.IntegerField(choices=[(1, '定时'), (2, '立即'), (3, '草稿')], default=1),
        ),
    ]
